INSERT INTO usuarios (nome, email, senha, created_at, updated_at, deleted_at) VALUES
('João Silva', 'joao.silva@example.com', 'senha123', NOW(), NOW(), NULL),
('Maria Oliveira', 'maria.oliveira@example.com', 'senha456', NOW(), NOW(), NULL),
('Carlos Santos', 'carlos.santos@example.com', 'senha789', NOW(), NOW(), NULL),
('Ana Souza', 'ana.souza@example.com', 'senha321', NOW(), NOW(), NULL),
('Pedro Rocha', 'pedro.rocha@example.com', 'senha654', NOW(), NOW(), NULL),
('Juliana Mendes', 'juliana.mendes@example.com', 'senha987', NOW(), NOW(), NULL),
('Ricardo Lima', 'ricardo.lima@example.com', 'senha741', NOW(), NOW(), NULL),
('Fernanda Alves', 'fernanda.alves@example.com', 'senha852', NOW(), NOW(), NULL),
('Marcos Pereira', 'marcos.pereira@example.com', 'senha963', NOW(), NOW(), NULL),
('Larissa Costa', 'larissa.costa@example.com', 'senha147', NOW(), NOW(), NULL),
('Bruno Martins', 'bruno.martins@example.com', 'senha258', NOW(), NOW(), NULL),
('Patrícia Nogueira', 'patricia.nogueira@example.com', 'senha369', NOW(), NOW(), NULL),
('André Carvalho', 'andre.carvalho@example.com', 'senha159', NOW(), NOW(), NULL),
('Camila Barbosa', 'camila.barbosa@example.com', 'senha753', NOW(), NOW(), NULL),
('Vinícius Mendes', 'vinicius.mendes@example.com', 'senha852', NOW(), NOW(), NULL),
('Letícia Fernandes', 'leticia.fernandes@example.com', 'senha951', NOW(), NOW(), NULL),
('Fábio Rezende', 'fabio.rezende@example.com', 'senha753', NOW(), NOW(), NULL),
('Tatiane Duarte', 'tatiane.duarte@example.com', 'senha123', NOW(), NOW(), NULL),
('Gustavo Farias', 'gustavo.farias@example.com', 'senha456', NOW(), NOW(), NULL),
('Raquel Castro', 'raquel.castro@example.com', 'senha789', NOW(), NOW(), NULL);

INSERT INTO estudantes (nome_completo, endereco, bairro, responsavel, parentesco_id, whatsapp, created_at, updated_at) VALUES
('Carlos Silva', 'Rua A, 123', 'Centro', 'Ana Silva', 1, '11987654321', NOW(), NOW()),
('Mariana Souza', 'Rua B, 456', 'Jardim', 'Pedro Souza', 2, '11976543210', NOW(), NOW()),
('João Oliveira', 'Rua C, 789', 'Vila Nova', 'Maria Oliveira', 3, '11965432109', NOW(), NOW()),
('Fernanda Costa', 'Rua D, 321', 'Bela Vista', 'Carlos Costa', 4, '11954321098', NOW(), NOW()),
('Rafael Mendes', 'Rua E, 654', 'Centro', 'Juliana Mendes', 5, '11943210987', NOW(), NOW()),
('Laura Lima', 'Rua F, 987', 'Vila Nova', 'Ricardo Lima', 6, '11932109876', NOW(), NOW()),
('Bruno Martins', 'Rua G, 741', 'Jardim', 'Patricia Martins', 7, '11921098765', NOW(), NOW()),
('Gabriela Alves', 'Rua H, 852', 'Bela Vista', 'Fernando Alves', 8, '11910987654', NOW(), NOW()),
('Thiago Rocha', 'Rua I, 963', 'Centro', 'Vanessa Rocha', 9, '11909876543', NOW(), NOW()),
('Camila Ferreira', 'Rua J, 147', 'Vila Nova', 'Marcos Ferreira', 10, '11908765432', NOW(), NOW()),
('Ricardo Santos', 'Rua K, 258', 'Jardim', 'Roberta Santos', 1, '11907654321', NOW(), NOW()),
('Aline Cardoso', 'Rua L, 369', 'Bela Vista', 'Lucas Cardoso', 2, '11906543210', NOW(), NOW()),
('Gustavo Nunes', 'Rua M, 753', 'Centro', 'Tatiane Nunes', 3, '11905432109', NOW(), NOW()),
('Juliana Ribeiro', 'Rua N, 951', 'Jardim', 'Anderson Ribeiro', 4, '11904321098', NOW(), NOW()),
('Fábio Teixeira', 'Rua O, 852', 'Vila Nova', 'Sandra Teixeira', 5, '11903210987', NOW(), NOW()),
('Natália Barbosa', 'Rua P, 147', 'Bela Vista', 'Eduardo Barbosa', 6, '11902109876', NOW(), NOW()),
('Leonardo Moreira', 'Rua Q, 258', 'Centro', 'Camila Moreira', 7, '11901098765', NOW(), NOW()),
('Beatriz Lopes', 'Rua R, 369', 'Jardim', 'Rodrigo Lopes', 8, '11909876544', NOW(), NOW()),
('Vinícius Araújo', 'Rua S, 753', 'Vila Nova', 'Fabiana Araújo', 9, '11908765433', NOW(), NOW()),
('Isabela Duarte', 'Rua T, 951', 'Bela Vista', 'Gustavo Duarte', 10, '11907654322', NOW(), NOW());

INSERT INTO parentescos (nome, created_at, updated_at) VALUES
('Pai', NOW(), NOW()),
('Mãe', NOW(), NOW()),
('Avô', NOW(), NOW()),
('Avó', NOW(), NOW()),
('Tio', NOW(), NOW()),
('Tia', NOW(), NOW()),
('Irmão', NOW(), NOW()),
('Irmã', NOW(), NOW()),
('Padrasto', NOW(), NOW()),
('Madrasta', NOW(), NOW());
